version: 0.2

phases:

  install:
    runtime-versions:
        dotnet: 5.0
            
  pre_build:
    commands:
      - dotnet restore NoNameApp/NoNameApp.sln
  build:
    commands:
      - dotnet build NoNameApp/NoNameApp.sln
      - dotnet publish -c release -o ./build_output NoNameApp/API/API.csproj
  post_build:
    commands:
      - cp aws-windows-deployment-manifest.json ./build_output/.
artifacts:
  files:
    - '**/*'
  base-directory: build_output