version: 0.2

phases:
  build:
    commands:
      - dotnet restore NoNameApp/API/API.csproj
      - dotnet build NoNameApp/API/API.csproj
      - dotnet publish -c release -o ./build_output NoNameApp/API/API.csproj
      - cp aws-windows-deployment-manifest.json ./build_output.
artifacts:
  files:
    - '/**/*'
  base-directory: build_output