version: 0.2

phases:
  pre_build:
    commands:
      - dotnet restore NoNameApp/API/API.csproj
      - dotnet build NoNameApp/API/API.csproj
  build:
    commands:
      - dotnet publish -c release -o ./build_output NoNameApp/API/API.csproj
artifacts:
  files:
    - '**/*'
  name: nna-api-build-$(date +%Y-%m-%d) 