version: 0.2

phases:
  build:
    commands:
      - dotnet restore NoNameApp-API/API/API.csproj
      - dotnet build NoNameApp-API/API/API.csproj
artifacts:
  files:
    - .\bin\Debug\netcoreapp3.1\*