version: 0.2

phases:
  pre_build:
    commands:
      - dotnet restore NoNameApp/API/API.csproj
      - dotnet build NoNameApp/API/API.csproj
  build:
    commands:
      - dotnet publish -c release -o ./build_output NoNameApp/API/API.csproj
artifacts:
  files:
    - NoNameApp/API/bin/QA/netcoreapp3.1/**/*